DF="~/Developer/dotfiles"
alias vi="nvim"
alias bashrc="cd $DF && vi .bashrc && cd -"
alias nvim-conf="cd $DF/nvim && vi init.lua && cd -"
alias update-dotfiles="cp -r $DF/nvim ~/AppData/Local/ && cp $DF/.bashrc ~/ && source ~/.bashrc"
